version: '3'

networks:
  livekit-net:
    driver: bridge

services:
  # Redis for LiveKit SIP server
  redis:
    image: redis:alpine
    networks:
      - livekit-net
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes

  # LiveKit server
  livekit:
    image: livekit/livekit-server:latest
    networks:
      - livekit-net
    command: --dev --bind 0.0.0.0 --node-ip host.docker.internal
    environment:
      - "LIVEKIT_KEYS=devkey: secret"
    ports:
      - "7880:7880"      # HTTP port
      - "7881:7881/tcp"  # WebRTC TCP port
      - "7882:7882/udp"  # WebRTC UDP port
    restart: unless-stopped
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # LiveKit SIP server
  livekit-sip:
    image: livekit/sip:latest
    networks:
      - livekit-net
    depends_on:
      - livekit
      - redis
    command: ["--config", "/sip/config.yaml"]
    ports:
      - "5060:5060/udp"  # SIP signaling port
      - "5080:5080"      # HTTP API port
    volumes:
      - ./livekit-sip-config.yaml:/sip/config.yaml
    environment:
      - SIP_TRUNK_ID=local-trunk
    restart: unless-stopped

  # Backend service
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   networks:
  #     - livekit-net
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   environment:
  #     - LIVEKIT_HOST=livekit:7880
  #     - LIVEKIT_API_KEY=devkey
  #     - LIVEKIT_API_SECRET=secret
  #     - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
  #     - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
  #     - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
  #     - TWILIO_TRUNK_SID=${TWILIO_TRUNK_SID}
  #     - SIP_TRUNK_ID=local-trunk
  #   depends_on:
  #     - livekit
  #     - livekit-sip
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

  # Frontend application
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   networks:
  #     - livekit-net
  #   ports:
  #     - "4200:80"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - backend