version: '3'

services:
  # Redis for LiveKit SIP server
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - livekit-network

  # LiveKit server
  livekit:
    image: livekit/livekit-server:latest
    command: --dev --bind 0.0.0.0 --node-ip livekit
    environment:
      - "LIVEKIT_KEYS=devkey: secret"
      - "LIVEKIT_SERVER_DISABLE_CORS=true"
      - "LIVEKIT_PORT=7880"
      - "LIVEKIT_RTC_PORT=7882"
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "7880:7880"
      - "7882:7882/udp"
    networks:
      - livekit-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # LiveKit SIP server
  livekit-sip:
    image: livekit/sip:latest
    depends_on:
      - livekit
      - redis
    command: ["--config", "/sip/config.yaml"]
    volumes:
      - ./livekit-sip-config.yaml:/sip/config.yaml
    environment:
      - SIP_TRUNK_ID=local-trunk
    restart: unless-stopped
    networks:
      - livekit-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - LIVEKIT_HOST=livekit:7880
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=secret
      - TWILIO_ACCOUNT_SID=AC795b72a1fd1d4d84558b27d091bf2b36
      - TWILIO_AUTH_TOKEN=d8b9eb3f389cab6841d151e451551baa
      - TWILIO_PHONE_NUMBER=+14322878106
      - TWILIO_TRUNK_SID=TK5e027325026cab68bc52f419561e19b3
      - TWILIO_TERMINATION_URI=aiagenticlivekit.pstn.twilio.com
      - TWILIO_CREDENTIAL_LIST_USERNAME=Livekit
      - TWILIO_CREDENTIAL_LIST_PASSWORD=Livekitpassword123
      - DEEPGRAM_URL=http://localhost:9012
    depends_on:
      - livekit
      - livekit-sip
    restart: unless-stopped
    networks:
      - livekit-network

  # Frontend application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - PORT=4200
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - livekit-network

networks:
  livekit-network:
    driver: bridge