# LiveKit SIP Server Configuration
log_level: info

# LiveKit connection
livekit:
  url: ws://livekit:7880
  api_key: devkey
  api_secret: secret

# Redis configuration
redis:
  address: redis:6379
  db: 0
  
# SIP configuration
sip:
  # SIP server binding address
  addr: 0.0.0.0:5060
  network: udp
  realm: livekit-sip.local
  
  # HTTP management API
  http_addr: 0.0.0.0:5080
  
  # Audio configuration - explicitly enable bidirectional audio
  audio:
    enabled: true
    publish: true     # Send audio to SIP participants
    subscribe: true   # Receive audio from SIP participants
    sample_rate: 8000 # Standard telephony sample rate
    channels: 1       # Mono audio for telephony

  # Outbound SIP settings
  outbound:
    enabled: true
    from: "LiveKit SIP <sip:livekit@livekit-sip.local>"
    default_trunk_id: local-trunk
# ASR (Automatic Speech Recognition) configuration
asr:
  provider: deepgram
  enabled: true
  language: en-US

  # TTS (Text-to-Speech) configuration
  tts:
    provider: deepgram
    enabled: true
    voice: female-1
    language: en-US

# Deepgram configuration for ASR/TTS
deepgram:
  url: http://host.docker.internal:9012  # Port-forwarding to stage Kubernetes cluster
  api_key: null
  model: general
  tier: enhanced
  timeout_ms: 30000
  fallback_provider: null
  retry_count: 3
  retry_delay_ms: 1000

# Trunk configurations
trunks:
  - id: local-trunk
    type: generic
    domain: aiagenticlivekit.pstn.twilio.com
    # Updated to match the actual termination URI
    uri: "sip:${TWILIO_TRUNK_SID}@aiagenticlivekit.pstn.twilio.com"
    # Enable debugging for this trunk
    debug: true
    # Add realm to match the configured domain
    realm: aiagenticlivekit.pstn.twilio.com